{% set name = "wurlitzer" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 86a510c0d34fcc9786ad1a9f557ac980f30ef2f821a75c2e4333311e0fd9cd76

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - wurlitzer

about:
  home: https://github.com/minrk/wurlitzer
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Capture C-level stdout/stderr in Python'

extra:
  recipe-maintainers:
    - minrk
    - bjodah
    - asmeurer
